In [2]:
# numpy編
import numpy as np

In [6]:
# listの生成
print(np.arange(3))
print(np.arange(3, 10))
# 増分指定
print(np.arange(3, 10, 2))
# 要素数指定
print(np.linspace(0, 5, 10))

[0 1 2]
[3 4 5 6 7 8 9]
[3 5 7 9]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
